/* DESENVOLVER UM PROGRAMA QUE DÊ OS VALORES DE X NOS QUAIS OCORRE A INTERCECÇÃO ENTRE FUNÇÕES PARA TODO VALOR DE -5=<X<=5
PROCESSOS DO PROGRAMA: O ALGORÍTMO DEVE SER CAPAZ DE RESOLVER AS DUAS FUNCÕES
O PROGRAMA DEVE COMPARAR OS VALORES DAS DUAS FUNCOES
O PROGRAMA DEVE ENCONTRAR TODOS OS VALORES DE X NOS QUAIS 	f(x)=g(x)
O ALGORITMO DEVE MOSTRAR AO USUARIO OS TAIS VALORES DE X
TUDO ISTO PARA    -5=<X<=5 */


#include <stdio.h>

main()
{
  float fx;//DECLARANDO AS VARIÁVEIS QUE TESTARÃO OS VALORES DE Y
  float gx;
  float X;//DECLARANDO OS VALORES DE X QUE SERÃO RESPONSÁVEIS PELA INTERCECÇÃO
  
 
 fx=2*X	;         // FUNÇAO f(x)
 gx= -(X*X)+(4*X);  // FUNÇÃO g(x)
 
 
 for(X=-5;X<=5;X++);
 { 
 if(fx==gx)
 printf("%f",X);
 else
 printf("nao tem",X);
 }
	
	
	
}



